package com.eemanapp.fuoexaet.utils

class Constants {

    companion object{
        const val USER_ID = "user_id"
        const val USER_WHO = "user_who"
        const val STUDENT = "Student"
        const val SECURITY = "Security"
        const val COORDINATOR = "Student_Coordinator"
        const val USER = "User"
        const val REQUEST = "Request"
        const val REQUEST_ID = "Request_Id"
        const val REQUESTER_USER_ID = "Requester_User_Id"
        const val ALL_REQUESTS = "All_Student_Requests"

        const val USER_FIRSTNAME = "User_First_Name"
        const val USER_LASTNAME = "User_Last_Name"
        const val USER_SCHOOLID = "User_School_Id"
        const val USER_EMAIL = "User_Email"
        const val USER_PHONENUMBER = "User_Phone_Number"
        const val USER_PROGRAMME = "User_Programme"
        const val USER_COLLEGE = "User_College"
        const val USER_DEPT = "User_College"
        const val USER_ENTRYYEAR = "User_Year"
        const val USER_HALL = "User_Hall"
        const val USER_HALL_NUMBER = "User_Hall_Number"
        const val USER_IMAGEURL = "User_Image_Url"
        const val USER_USERWHO = "User_User_Who"
        const val USER_UNIQUEID = "User_Unique_Id"
        const val USER_NOT_PAY = "User_Never_Pay"
        const val HAS_USER_PAY = "Has_User_Pay"
        const val USER_PAYMENT_REF = "User_Payment_Ref"
        const val FCM_TOKEN = "Fcm_Token"
        const val USER_CREATED_BY_WHO = "User_Created_By_Who"
        const val USER_CREATED_WHEN = "User_Created_When"
        const val PASSWORD = "Password"
        const val PROGRAMME = "Programme"
        const val STUDENT_REQUEST_CHANNEL = "Student Requests"
        const val STUDENT_REQUEST_CHANNEL_DESC = "Channel for getting notifications on requests made by the students"
        const val REQUEST_NOTIFICATION_CHANNEL_ID = "Student_Requests"
        const val ACTION_APPROVE = "Action_Approve"
        const val ACTION_DECLINE = "Action_Decline"
        const val APPROVE = "Approve"
        const val DECLINE = "Decline"
    }
}